### ISSUE TITLE
use tracer from Config for extracting headers

### ISSUE THREAD

**Issue by andrascz** [aschenmaker/fiber-opentracing#2]
seems inconsistent using the GlobalTracer() instead of the instance provided by the config.

**Comment by aschenmaker** [comment]
hi, andrascz.
I checked my example. I used the ` GlobalTracer` instead of the instance in config.
I will give another example for it.
thank u, best wish.

**Comment by andrascz** [comment]
Sorry, maybe I was not clear enough.

```go
// Extract trace-id from header
spop := HeaderExtractor(header)

if spop != nil {
	span = tracer.StartSpan(tracsacationName, spop)
} else {
	span = tracer.StartSpan(tracsacationName)
}
```
should be
```go
// Extract trace-id from header
sc, err := tracer.Extract(opentracing.HTTPHeaders, opentracing.HTTPHeadersCarrier(hdr))

if err == nil {
	span = tracer.StartSpan(tracsacationName, opentracing.ChildOf(sc))
} else {
	span = tracer.StartSpan(tracsacationName)
}
```

By the way `tracsacationName` should be `transactionName`

**Comment by aschenmaker** [comment]
sorry!  It's my mistake.
I forgot to use the tracer from the config.
Thank you.

**Comment by andrascz** [comment]
One correction you need to switch `hdr` to `header` in the proposed code.

**Comment by aschenmaker** [comment]
Thank u!
I fixed it.
