### ISSUE TITLE
option to not create span if no downstream span is available

### ISSUE THREAD

**Issue by andrascz** [aschenmaker/fiber-opentracing#3]
When using Fiber in a microservice environment, it is beneficial if root spans are not created on the service level as the trace sampling is done at the ingress level.
So in this case it is counter intuitive to create a new span if there is none in the request.
There is a workaround with the Filter function, but it would be nice to be able to configure this, to not work twice on the headers.

**Comment by aschenmaker** [comment]
I probably know what you mean. If the root span not create at ingress level, the following fiber service should not create new span. 
Are you willing to add this feature by creating a pull request? 
thanks.

**Comment by andrascz** [comment]
Yeah, exactly. I will cut a PR then.

**Comment by aschenmaker** [comment]
thanks a lot! @andrascz
